config/routes.rb
Rails.application.routes.draw do
  resources :greetings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[ show edit update destroy ]

  # GET /greetings or /greetings.json
  def index
    @greetings = Greeting.all
  end

  # GET /greetings/1 or /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings or /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to @greeting, notice: "Greeting was successfully created." }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1 or /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to @greeting, notice: "Greeting was successfully updated." }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1 or /greetings/1.json
  def destroy
    @greeting.destroy
    respond_to do |format|
      format.html { redirect_to greetings_url, notice: "Greeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greeting
      @greeting = Greeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def greeting_params
      params.require(:greeting).permit(:name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/_form.html.erb
<%= form_with(model: greeting, local: true) do |form| %>
  <% if greeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
      <% greeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/edit.html.erb
<h1>Editing Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Show', @greeting %> |
<%= link_to 'Back', greetings_path %>

app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>あいさつを投稿しよう</h1>
<p>現在のあいさつ数は<%= @greetings.count %>です。</p>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>メッセージ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @greetings.each do |greeting| %>
      <tr>
        <td><%= greeting.name %></td>
        <td><%= greeting.message %></td>
        <td><%= link_to '表示', greeting %></td>
        <td><%= link_to '編集', edit_greeting_path(greeting) %></td>
        <td><%= link_to '削除', greeting, method: :delete, data: { confirm: '削除してもいい？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規あいさつを作成', new_greeting_path %>

app/views/greetings/new.html.erb
<h1>New Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Back', greetings_path %>

app/views/greetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @greeting.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @greeting.message %>
</p>

<%= link_to 'Edit', edit_greeting_path(@greeting) %> |
<%= link_to 'Back', greetings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>